version: 2

sources:
  - name: natality
    database: "{{ env_var('DBT_DATABASE', 'natality-data-project-dez') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'natality_data') }}"
    tables:
      - name: natality_data  # Must match EXACT table name in BigQuery
        description: "US Natality records"
        columns:
          - name: unique_id
          - name: dob_yy
          - name: dob_date
          - name: dbwt
          - name: mager
          - name: mager9

models:
  - name: stg_birth_data
    description: >
      Cleaned staging model for birth records containing standardized fields
      for mother demographics and baby birth characteristics.
    columns:
      - name: unique_id
        description: Generated unique identifier for each birth record
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: dob_yy
        description: Year of birth
        tests:
          - not_null

      - name: dob_date
        description: Synthetic date column for partitioning (YYYY-MM-DD format)
        tests:
          - not_null

      - name: dbwt
        description: Baby birth weight in grams
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "dbwt BETWEEN 500 AND 6000"
              severity: warn

      - name: mager
        description: Mother's exact age in years
        tests:
          - dbt_utils.expression_is_true:
              expression: "mager BETWEEN 15 AND 50"
              severity: warn

      - name: mager9
        description: Mother's age group (9 categories)
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9]
              severity: warn

      - name: meduc
        description: Mother's education level
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9]
              severity: warn
              description: "1=8th grade or less, 2=9-12th grade, ..., 9=unknown"

      - name: mrace6
        description: Mother's race (6 categories)
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6]
              severity: warn
              description: "1=White, 2=Black, 3=AIAN, 4=Asian, 5=NHOPI, 6=Multiple"

  - name: stg_mother_age_distribution
    description: >
      Percentage distribution of births by mother's age group for 2023 data.
      Used for demographic analysis.
    columns:
      - name: mother_age_group
        description: Categorical age group (1-9)
      - name: count
        description: Number of births in this age group
      - name: percentage
        description: Percentage of total births

  - name: stg_avg_mother_age_by_year
    description: >
      Average mother age by birth year from 2018-2023.
      Shows trends in maternal age over time.
    columns:
      - name: year
        description: Year of birth
      - name: avg_mother_age
        description: Average age of mothers this year
      - name: record_count
        description: Number of births analyzed

  - name: stg_baby_weight_by_age_group
    description: >
      Average baby weight stratified by mother's age group.
      Uses all available data years.
    columns:
      - name: mother_age_group
        description: Categorical age group (1-9)
      - name: avg_baby_weight_grams
        description: Mean birth weight for this age group
      - name: record_count
        description: Number of births in calculation