# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'natality_analysis'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# Configure global variables
vars:
  project_id: 'natality-data-project-dez'  # Your GCP project ID
  dataset: 'natality_data'                # Your BigQuery dataset name
  # Define valid values for categorical fields
  mother_age_groups: [1, 2, 3, 4, 5, 6, 7, 8, 9]
  mother_race_codes: [1, 2, 3, 4, 5, 6]
  education_codes: [1, 2, 3, 4, 5, 6, 7, 8, 9]

# File paths (keep these standard)
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory for compiled SQL files
clean-targets:         # directories to remove with `dbt clean`
  - "target"
  - "dbt_packages"

# Model configurations
models:
  natality_analysis:
    # Configurations for all models
    +materialized: view  # Default to views (override in specific models if needed)
    
    # Staging layer - light transformations
    staging:
      +materialized: view
